import axios from 'axios'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useEffect, useState } from 'react';
import {pressCodes} from '../../../server/pressCode';
import TinyBarChart from '../../../src/components/TinyBarChart';
import TinyLineChart from '../../../src/components/TinyLineChart';
import {motion} from 'framer-motion';


export default function PressDetail({id}) {
  const [press,setPress]=useState(null);
  useEffect(()=>{
    axios.get(`http://localhost:4000/press/${id}`)
    .then(res=>setPress(res.data))
    .catch(err=>console.log(err.message))
  },[])
  console.log(id)
  return (
    <div className='p-2'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className=' bg-primary-dark-green h-20 flex justify-start items-center rounded-sm drop-shadow-xl p-2 sticky top-2 bg-opacity-80 z-10'>
        <nav className='flex justify-start items-center gap-12'>
          <div>
            <Image src="/images/logo.webp" alt="sisako logo" width={60} height={60}/>
          </div>
          <div className='flex-1 flex justify-start items-center gap-9'>
            <Link legacyBehavior href="/press"><a className='py-3 px-3 rounded-md hover:bg-primary-light-green transition-all duration-300'>پرس ها</a></Link>
            <Link legacyBehavior href="/die"><a className='py-3 px-3 rounded-md hover:bg-primary-light-green transition-all duration-300'>قالب ها</a></Link>
            <Link legacyBehavior href="/personnel"><a className='py-3 px-3 rounded-md hover:bg-primary-light-green transition-all duration-300'> پرسنل</a></Link>
          </div>
        </nav>
      </header>
      {press && 
      <main className='grid grid-cols-1 lg:grid-cols-2  gap-10 py-4  mt-10 mb-20 container mx-auto'>
        {/* one press card */}
         <motion.div whileHover={{scale:1.1}} initial={{y:'-100vw'}} animate={{y:0}} transition={{duration:1,type: "spring", stiffness: 60, damping: 7}} className='grid grid-cols-2 bg-primary-light-green drop-shadow-2xl shadow-primary-dark-green shadow-md p-2 rounded-md gap-4'>
           <div className='aspect-w-1 aspect-h-1 '>
             <img src={press.image} alt="press" className='w-full h-full object-center object-cover rounded-sm' />
           </div>
           <div className='flex flex-col gap-10 justify-center items-start'>
             <div className='flex items-center gap-2'>
               <h2>کد پرس :</h2>
               <p className='font-bold'>{press.id}</p>
             </div>
             <div className='flex items-center gap-2'>
               <h2>مشخصات پرس :</h2>
               <p className='font-bold'>{press.name}</p>
             </div>
             <div className='flex items-center gap-2'>
               <h2>کشور سازنده:</h2>
               <p className='font-bold'>{press.maker}</p>
             </div>
           </div>
         </motion.div>
         {/* one press zarb */}
         <motion.div whileHover={{scale:1.1}} initial={{y:'-100vw'}} animate={{y:0}} transition={{duration:1,type: "spring", stiffness: 60, damping: 7}} className='p-2 bg-primary-light-green rounded-md'>
           <h2 className='text-center font-bold mb-8'>تعداد ضرب پرس {press.id}</h2>
           <TinyBarChart data={press.numberOfProduction} title="OEE"/>
         </motion.div>
         {/* one press failrure times */}
         <motion.div whileHover={{scale:1.1}} initial={{y:'100vw'}} animate={{y:0}} transition={{duration:1,type: "spring", stiffness: 60, damping: 7}} className='p-2 bg-primary-light-green rounded-md'>
           <h2 className='text-center font-bold mb-8'>زمان خرابی پرس {press.id} در ماه</h2>
           <TinyLineChart data={press.failureTime} title="OEE"/>
         </motion.div>
         {/* one press priduction times */}
         <motion.div whileHover={{scale:1.1}} initial={{y:'100vw'}} animate={{y:0}} transition={{duration:1,type: "spring", stiffness: 60, damping: 7}} className='p-2 bg-primary-light-green rounded-md'>
           <h2 className='text-center font-bold mb-8'>زمان تولید پرس {press.id} در ماه</h2>
           <TinyLineChart data={press.productionTime} title="OEE"/>
         </motion.div>
       
       
      </main>
       }
      
    <footer className='fixed bottom-0 right-0 left-2 bg-primary-dark-green h-20 w-full flex justify-center items-center'>
        <p>با بیش از بیست سال سابقه کار در صنعت خودرو</p>
      </footer>
    </div>
  )
};
export async function getStaticPaths() {
    const paths=pressCodes.map(item=>{
        return {params:{slug:item}}; 
    })
  return {
    paths:paths,
    fallback: false,
  }
};
export async function getStaticProps({params}) {
  const id=(params.slug)
  return {
    props: {
      id
    }, 
  }
}
