import axios from 'axios';
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useEffect, useState } from 'react';
import TinyBarChart from '../../../../../../../src/components/TinyBarChart';
import TinyLineChart from '../../../../../../../src/components/TinyLineChart';
import {motion} from 'framer-motion'

const sectionAnimation={
  "hidden":{
    opacity:0
  },
  "visible":{
    opacity:1,
    transition:{
      duration:2
    }
  },
  "hover":{
    scale:1.05,
    transition:{
      duration:0.5,stiffness:400,type: "spring", bounce: 4,damping:6,mass: 3
    }
  }
}


export default function Part({data}) {
  console.log(data)
    const [stage,setStage]=useState({data:null,error:"",loading:false});
    console.log(stage)
   useEffect(()=>{
    setStage({data:null,errorr:"",loading:true})
    axios.get(`http://localhost:4000/die?customer=${data.customerSlug}&product=${data.productSlug}&part=${data.partSlug}&stage=${data.stageSlug}&number=${data.dieSlug}`)
    .then((res)=>{
        console.log(res.data)
        setStage({data:res.data,error:"",loading:false});
    })
    .catch(err=>{
        setStage({data:null,error:err.message,loading:false})
        console.log(err.message)
    })
   },[]);
   console.log(stage.data)
  return (
    <div className='p-2'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className=' bg-primary-dark-green h-20 flex justify-start items-center rounded-sm drop-shadow-xl p-2 sticky top-2 bg-opacity-80 z-10'>
        <nav className='flex justify-start items-center gap-12'>
          <div>
            <Image src="/images/logo.webp" alt="sisako logo" width={60} height={60}/>
          </div>
          <div className='flex-1 flex justify-start items-center gap-9'>
            <Link legacyBehavior href="/press"><a className='py-3 px-3 rounded-md hover:bg-primary-light-green transition-all duration-300'>پرس ها</a></Link>
            <Link legacyBehavior href="/die"><a className='py-3 px-3 rounded-md hover:bg-primary-light-green transition-all duration-300'>قالب ها</a></Link>
            <Link legacyBehavior href="/personnel"><a className='py-3 px-3 rounded-md hover:bg-primary-light-green transition-all duration-300'> پرسنل</a></Link>
          </div>
        </nav>
      </header>
      <main className='grid grid-cols-1 lg:grid-cols-2  gap-10 py-4  mt-10 mb-20 container mx-auto'>
       
    {stage.data &&   
      stage.data.map(item=>(
        <>
<motion.div variants={sectionAnimation} initial="hidden" animate="visible" whileHover="hover" key={item.id} className='bg-primary-light-green drop-shadow-lg p-2 rounded-md'>
          <div className='grid grid-cols-2  gap-4 justify-center items-center h-full'>
            <div className='aspect-w-1 aspect-h-1'><img src={item.image} alt={item.stage} className='w-full h-full object-center object-cover rounded-sm' /></div>
            <div className='flex-1 flex justify-center items-center  text-2xl '>
          <p>  قالب  شماره  {item.number} </p>
          <h2> {item.stage} </h2>
        </div>
          </div>
          {/* one die zarb */}
    </motion.div>
    <div className='p-2 bg-primary-light-green rounded-md'>
    <h2 className='text-center font-bold mb-8'>تعداد ضرب قالب  {item.id}</h2>
    <TinyBarChart data={item.numberOfProduction} title="number of production"/>
  </div>
  {/* one die failrure times */}
  <div className='p-2 bg-primary-light-green rounded-md'>
    <h2 className='text-center font-bold mb-8'>مدت زمان خرابی قالب  {item.id} در ماه</h2>
    <TinyLineChart data={item.failureTime} title="failure time"/>
  </div>
  {/* number of failure die  */}
  <div className='p-2 bg-primary-light-green rounded-md'>
    <h2 className='text-center font-bold mb-8'>  تعداد دفعات خرابی قالب {item.id} در ماه</h2>
    <TinyBarChart data={item.numberOfFailure} title="number of failure"/>
  </div>
  </>
      ))
      
    }

    </main>
      
    <footer className='fixed bottom-0 right-0 left-2 bg-primary-dark-green h-20 w-full flex justify-center items-center'>
        <p>با بیش از بیست سال سابقه کار در صنعت خودرو</p>
      </footer>
    </div>
  )
}
export async function getServerSideProps({query}) {
    // Fetch data from external API
    const data=query;
    console.log(query)
  
    // Pass data to the page via props
    return { props: {data :data } }
  }