import axios from 'axios'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useEffect, useState } from 'react'
import PersonnelFilter from '../src/components/PersonnelFilter'


export default function AllPersonnel() {
  const [personnel,setPersonnel]=useState({data:null,error:null,loading:false});
  const [showPersonnel,setShowPersonnel]=useState(null);
  const [filters,setFilters]=useState({level:"",position:""})
  useEffect(()=>{
    setPersonnel({data:null,error:null,loading:true})
     axios.get(`http://localhost:4000/personnel`)
     .then(res=>setPersonnel({data:res.data,error:null,loading:false}))
     .catch(err=>setPersonnel({data:null,error:err,loading:false}))
  },[]);
  useEffect(()=>{
    if(personnel.data){
        let filteredPersonnel=personnel.data;
        filteredPersonnel=filterLevel(filteredPersonnel);
        filteredPersonnel=filterPosition(filteredPersonnel);
        setShowPersonnel(filteredPersonnel)
    }
  },[personnel,filters]);
  // filter the level
  const filterLevel=(arr)=>{
    if(filters.level===""){
        return arr
    }else{
      return  arr.filter(item=>item.level===filters.level)
    }
  };
  // filter the positioin
  const filterPosition=(arr)=>{
    if(filters.position===""){
        return arr
    }else{
      return  arr.filter(item=>item.position===filters.position)
    }
  }
  const changeHandler=(e)=>{
    setFilters({...filters,[e.target.name]:e.target.value})
  }
  return (
    <div className='p-2'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className=' bg-primary-dark-green h-20 flex justify-start items-center rounded-sm drop-shadow-xl p-2 sticky top-2 bg-opacity-80 z-10'>
        <nav className='flex justify-start items-center gap-12'>
          <div>
            <Image src="/images/logo.webp" alt="sisako logo" width={60} height={60}/>
          </div>
          <div className='flex-1 flex justify-start items-center gap-9'>
            <Link legacyBehavior href="/press"><a className='py-3 px-3 rounded-md hover:bg-primary-light-green transition-all duration-300'>پرس ها</a></Link>
            <Link legacyBehavior href="/die"><a className='py-3 px-3 rounded-md hover:bg-primary-light-green transition-all duration-300'>قالب ها</a></Link>
            <Link legacyBehavior href="/personnel"><a className='py-3 px-3 rounded-md hover:bg-primary-light-green transition-all duration-300'> پرسنل</a></Link>
          </div>
        </nav>
      </header>
      <div className='container mx-auto max-w-xs'>
      <PersonnelFilter changeHandler={changeHandler} />
      </div>
    <main className='grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-10 py-4  mt-10 mb-20 container mx-auto'>
    {personnel.data && showPersonnel&& showPersonnel.map(item=>(
      <div key={item.id} className='bg-primary-light-green drop-shadow-lg p-2 rounded-md'>
      
          <div className='grid grid-cols-2  gap-8'>
            <div className='aspect-w-1 aspect-h-1 '><img src={item.image} alt='personnel' className='w-full h-full object-center object-contain' /></div>
            <div className='flex flex-col justify-center items-center gap-4'>
              <h3 className='font-bold text-xl'>{item.name}</h3>
              <h3 className='font-bold text-xl'>{item.position}</h3>
              <h3 className='font-bold text-xl'>{item.level}</h3>
            </div>
          </div>
    </div>
    ))}
       
    </main>
      
    <footer className='fixed bottom-0 right-0 left-2 bg-primary-dark-green h-20 w-full flex justify-center items-center'>
        <p>با بیش از بیست سال سابقه کار در صنعت خودرو</p>
      </footer>
    </div>
  )
};
